# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fa1838b7c5261bbfea8e31862eb6bcd9168308b79121ea8b152e6486109dfef106453a45b966796a92a87958873869afa0bfac729ad9c7afeafbeb6170b272d

test:
  secret_key_base: 4053a3eaf5065ba6b7bd063d7309d0f5a2f945fbafbd37ef327a1dba31bf4ec76b08e57f3ec89c7334790a7b4007a857075c97d8ee54d4f8cd7b0b53fe095adc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
